// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3OqKxOGGLWqgE3gzF0a8FiGM-qS2Je0k',
    appId: '1:277205083772:web:5a231a348eea88483d8bf9',
    messagingSenderId: '277205083772',
    projectId: 'fasih-b42cd',
    authDomain: 'fasih-b42cd.firebaseapp.com',
    storageBucket: 'fasih-b42cd.firebasestorage.app',
    measurementId: 'G-28D5DZ0CQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQSXGOBRqmFRFtD46P6Vz7t9Dn7AWQtyI',
    appId: '1:277205083772:android:b0a59df5cd1367bb3d8bf9',
    messagingSenderId: '277205083772',
    projectId: 'fasih-b42cd',
    storageBucket: 'fasih-b42cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZUtP7b_J1dtcUKTrMrncWRsg5yjMI70c',
    appId: '1:277205083772:ios:2f980b32772f4bfe3d8bf9',
    messagingSenderId: '277205083772',
    projectId: 'fasih-b42cd',
    storageBucket: 'fasih-b42cd.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZUtP7b_J1dtcUKTrMrncWRsg5yjMI70c',
    appId: '1:277205083772:ios:2f980b32772f4bfe3d8bf9',
    messagingSenderId: '277205083772',
    projectId: 'fasih-b42cd',
    storageBucket: 'fasih-b42cd.firebasestorage.app',
    iosBundleId: 'com.example.gradProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3OqKxOGGLWqgE3gzF0a8FiGM-qS2Je0k',
    appId: '1:277205083772:web:e3bba559f733ebcb3d8bf9',
    messagingSenderId: '277205083772',
    projectId: 'fasih-b42cd',
    authDomain: 'fasih-b42cd.firebaseapp.com',
    storageBucket: 'fasih-b42cd.firebasestorage.app',
    measurementId: 'G-0QSGKBXCHH',
  );

}